import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { Footer, Header } from "@/components/layout";
import { UIContainer } from "./UIContainer";
import "./globals.css";

const dmSans = DM_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Photosnap",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <UIContainer>
          <Header />
          {children}
          <Footer />
        </UIContainer>
      </body>
    </html>
  );
}
